package com.medstudy.backend.modules.notificacao.dto;
import com.medstudy.backend.core.constants.ValidationMessages;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Data Transfer Object representing a social notification response.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SocialNotificationResponseDTO {
    /**
     * The unique identifier of the notification.
     */
    @Schema(description = "Unique identifier of the notification record.", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID id;
    
    /**
     * The unique identifier of the user who received the notification.
     */
    @Schema(description = "Unique identifier of the user who received the notification.", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID userId;
    
    /**
     * The unique identifier of the user who sent the notification.
     */
    @Schema(description = "Unique identifier of the user who triggered and sent this notification.", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID senderId;
    
    /**
     * The name of the sender.
     */
    @Schema(description = "Display name of the user who triggered this notification, shown in the notification feed.", example = "Dr. John Smith")
    private String senderName;
    
    /**
     * The avatar preset ID of the sender.
     */
    @Schema(description = "Avatar preset identifier of the sender, used to render their profile picture in the notification item.", example = "avatar_07")
    private String senderAvatarPresetId;
    
    /**
     * The type of the notification.
     */
    @Schema(description = "Type of social notification event (e.g., FRIEND_REQUEST, BADGE_EARNED, COMPETITION_INVITE).", example = "FRIEND_REQUEST")
    private String type;
    
    /**
     * The message content of the notification.
     */
    @Schema(description = "Human-readable message describing the notification event, displayed in the notification list.", example = "Dr. John Smith sent you a friend request.")
    private String message;
    
    /**
     * Indicates whether the notification has been read.
     */
    @Schema(description = "Indicates whether the notification has been read by the recipient. Unread notifications appear highlighted in the UI.", example = "false")
    private Boolean isRead;
    
    /**
     * The timestamp when the notification was created.
     */
    @Schema(description = "Timestamp when the notification was generated by the system (ISO 8601).", example = "2024-05-10T14:22:00")
    private LocalDateTime createdAt;

}
