ALTER TABLE profiles ADD COLUMN is_public BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN share_streak BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN share_faculdade BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN share_total_questions BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN share_badges BOOLEAN NOT NULL DEFAULT TRUE;
