ALTER TABLE lessons 
ADD COLUMN sub_area VARCHAR(255),
ADD COLUMN data_aula DATE,
ADD COLUMN percent_acerto INTEGER,
ADD COLUMN reforco BOOLEAN DEFAULT FALSE,
ADD COLUMN revisao BOOLEAN DEFAULT FALSE;
