spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER:mock_user}
    password: ${MAILTRAP_PASS:mock_pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

gcp:
  project-id: ${GCP_PROJECT_ID}
  bucket-name: ${GCP_BUCKET_NAME}
  credentials:
    path: ${GCP_CREDENTIALS_PATH}

server:
  port: ${PORT:8080}
  max-http-header-size: 1MB
  compression:
    enabled: true
    min-response-size: 2048

jwt:
  secret: ${JWT_SECRET}
  expiration: 14400000

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN}
  public-key: ${MERCADOPAGO_PUBLIC_KEY}

app:
  premium-price: 49.90
