package com.medstudy.backend.modules.flashcard.dto;
import com.medstudy.backend.core.constants.ValidationMessages;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;
import lombok.Data;

import com.medstudy.backend.modules.flashcard.entity.FlashcardDifficulty;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Data Transfer Object for flashcard responses.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FlashcardResponse {
    
    /**
     * The unique identifier of the flashcard.
     */
    @Schema(description = "Unique identifier of the flashcard generated by the system.", example = "123e4567-e89b-12d3-a456-426614174000")
    private UUID id;
    
    /**
     * The subject area of the flashcard.
     */
    @Schema(description = "The major medical area to which this flashcard belongs (e.g., Internal Medicine, Surgery).", example = "Pediatrics")
    private String grandeArea;
    
    /**
     * The front content of the flashcard.
     */
    @Schema(description = "Content displayed on the front of the card: the question or term to be memorized.", example = "What is the Amoxicillin dose for Acute Otitis Media in children?")
    private Object frente;
    
    /**
     * The back content of the flashcard.
     */
    @Schema(description = "Content displayed on the back of the card: the answer, explanation or mnemonic.", example = "50 mg/kg/day, divided into 2-3 doses, for 10 days.")
    private Object verso;
    
    /**
     * The date of the next scheduled revision.
     */
    @Schema(description = "Scheduled date for the next revision of this flashcard, calculated by the spaced repetition algorithm.", example = "2024-06-15")
    private LocalDate proximaRevisao;
    
    /**
     * The difficulty of the last study session.
     */
    @Schema(description = "Difficulty level selected by the student in the last revision session (EASY, MEDIUM or HARD).", example = "MEDIUM")
    private FlashcardDifficulty dificuldadeUltima;
    
    /**
     * The current interval in days.
     */
    @Schema(description = "Current interval in days until the next revision, progressively calculated by the spaced repetition algorithm.", example = "7")
    private Integer intervaloAtual;

}
